spring.application.name=Offline-Backend

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-crimson-mode-a1ibrgd-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:neondb_owner}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:npg_VlbSXJk5ruzG}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.datasource.hikari.auto-commit=false

# Bank Server URL (default to localhost for dev, override for prod)
bank.server.url=${BANK_SERVER_URL:http://localhost:9090}
